### ISSUE TITLE
conveyor is using dsteem, dsteem must be moved into steemit org and proper security process applied for this practice to continue

### ISSUE THREAD

**Issue by sneak** [steemit/conveyor#20]

**Comment by jnordberg** [comment]
Not that I'm against this but why is dsteem special? We use 10+ other 3rd party libraries.

**Comment by sneak** [comment]
I guess it isn't but if we're going to begin the process of adopting it for official use we should bring it under the umbrella, no?

**Comment by jnordberg** [comment]
Yeah I'm up for it

cc @goldibex

**Comment by jnordberg** [comment]
Conveyor is only directly using dsteem as a devDependency now so closing this.
