### ISSUE TITLE
conveyor should implement a tagging system for usernames.

### ISSUE THREAD

**Issue by sneak** [steemit/conveyor#26]
spec:  (all calls require admin signature, this is an internal support system)

- call: `define_tag(tagname, description)`
- call: `get_users_by_tags(tagname) # one tag`
- call: `get_users_by_tags([tagname]) # list of tags, ANDed`
- call: `add_tag_by_user(username, tag)`
- call: `remove_tag_by_user(username, tag)`
- call: `get_tags_for_user(username)`

- table: taglist (id, name, desc, created)
- table: usertags (id, username, tagid)

The idea here is that `redeemer` and `faucet` and future blockchain followers and other things can add and remove tags to users based on their username, then other things (e.g. redeemer) can use the existence or nonexistence of a tag on a user to do stuff, e.g. not-re-delegate SP, or display a warning or error, or whatever.

Tags must be defined before they can be used, so that we can store a description of what that tag is specifically used for, because people cannot be trusted to use appropriately descriptive tag names.

Tags will probably be defined via admin CLI.

**Comment by sneak** [comment]
The first tag defined should be `make_site_unbearable`, and the first user tagged with it shall be left as an exercise to the reader.

**Comment by sneak** [comment]
I just realized that this should probably also support tagging based on session UUID, so that we can apply tags to user sessions before they have logged in or registered, and then `faucet` can inform `conveyor` that “session x has become username y” on registration, transferring/moving those tags over to their permanent username-based record (“shadow profile”).

**Comment by jnordberg** [comment]
I'd love to start using some document database from day one (DynamoDB perhaps) where we can store each users tags (and other things like user preferences) under one user document and then build indexing functions for `get_users_by_tag` etc. The write-on-read schematics needed to implement #17 work very well with this approach as well

**Comment by relativityboy** [comment]
We should track when tags are created for a specific user.
