### ISSUE TITLE
Create a tag for Steemit employees

### ISSUE THREAD

**Issue by pkattera** [steemit/conveyor#31]
As a user, 
I want to be able to see when posts and comments have been made by people at Steemit Inc,
so I can verify that the information can be trusted.

-----------------

This new tag can be assigned to Steemit employees and contractors.

This will enable us to:
- Test new features in production (alongside our new feature flags)
- Add a badge / insignia to employee usernames and profile pages denoting their association with Steemit Inc.
- Possibly create functionality in the future which helps employees adhere to the new code of conduct rules

**Comment by jnordberg** [comment]
Tags have been designed not to be readable from other than backend services (as per spec) we would need to allow users to read their own tags for this to be implemented (or proxy the tag reads via another backend api)

**Comment by pkattera** [comment]
Acceptance criteria:
– Display a badge next to Steemit employees who have opted in to be official 'employees'

**Comment by bnchdrff** [comment]
see 
https://github.com/steemit/condenser/issues/2776
